### ISSUE TITLE
Doesn't work on JSON requires??

### ISSUE THREAD

**Issue by rayHInstart** [peteward44/browserify-casesensitiverequire#1]
When using  browserify-casesensitiverequire on a json, I get the following error:

events.js:85
      throw er; // Unhandled 'error' event
            ^
SyntaxError: Unexpected token (2:8) (while browserify-casesensitiverequire was processing /Users/kh/kp/project/src/main/config/pc.json) while parsing file: /Users/kh/kp/project/src/main/config/pc.json
    at Parser.pp.raise (/Users/kh/kp/project/node_modules/browserify-casesensitiverequire/node_modules/browserify-transform-tools/node_modules/falafel/node_modules/acorn/dist/acorn.js:1745:13)
    at Parser.pp.unexpected (/Users/kh/kp/project/node_modules/browserify-casesensitiverequire/node_modules/browserify-transform-tools/node_modules/falafel/node_modules/acorn/dist/acorn.js:2264:8)
    at Parser.pp.semicolon (/Users/kh/kp/project/node_modules/browserify-casesensitiverequire/node_modules/browserify-transform-tools/node_modules/falafel/node_modules/acorn/dist/acorn.js:2243:59)
    at Parser.pp.parseExpressionStatement (/Users/kh/kp/project/node_modules/browserify-casesensitiverequire/node_modules/browserify-transform-tools/node_modules/falafel/node_modules/acorn/dist/acorn.js:2677:8)
    at Parser.pp.parseStatement (/Users/kh/kp/project/node_modules/browserify-casesensitiverequire/node_modules/browserify-transform-tools/node_modules/falafel/node_modules/acorn/dist/acorn.js:2462:160)
    at Parser.pp.parseBlock (/Users/kh/kp/project/node_modules/browserify-casesensitiverequire/node_modules/browserify-transform-tools/node_modules/falafel/node_modules/acorn/dist/acorn.js:2692:21)
    at Parser.pp.parseStatement (/Users/kh/kp/project/node_modules/browserify-casesensitiverequire/node_modules/browserify-transform-tools/node_modules/falafel/node_modules/acorn/dist/acorn.js:2443:19)
    at Parser.pp.parseTopLevel (/Users/kh/kp/project/node_modules/browserify-casesensitiverequire/node_modules/browserify-transform-tools/node_modules/falafel/node_modules/acorn/dist/acorn.js:2379:21)
    at parse (/Users/kh/kp/project/node_modules/browserify-casesensitiverequire/node_modules/browserify-transform-tools/node_modules/falafel/node_modules/acorn/dist/acorn.js:101:12)
    at module.exports (/Users/kh/kp/project/node_modules/browserify-casesensitiverequire/node_modules/browserify-transform-tools/node_modules/falafel/index.js:22:15)
    at Stream.<anonymous> (/Users/kh/kp/project/node_modules/browserify-casesensitiverequire/node_modules/browserify-transform-tools/lib/transformTools.js:172:21)
    at Stream.end (/Users/kh/kp/project/node_modules/browserify-casesensitiverequire/node_modules/browserify-transform-tools/lib/transformTools.js:93:30)
    at _end (/Users/kh/kp/project/node_modules/browserify-casesensitiverequire/node_modules/browserify-transform-tools/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/kh/kp/project/node_modules/browserify-casesensitiverequire/node_modules/browserify-transform-tools/node_modules/through/index.js:74:5)
    at DestroyableTransform.onend (/Users/kh/kp/project/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:537:10)
    at DestroyableTransform.g (events.js:199:16)

Any ideas on what this could be? The file parses fine as JSON.
Thanks :).

**Comment by peteward44** [comment]
This appears to be a problem with benbria/browserify-transform-tools, however i've managed to fix it by adding the 'jsFilesOnly' option to the makeRequireTransform() call. It still appears to process .json file requires though! Strange but it's fixed in v1.0.1 :)

**Comment by rayHInstart** [comment]
Cool!!! Thanks!
-Ray
